---
- name: Compress directory /path/to/foo/ into /path/to/foo.tgz
  archive:
    path: /tmp
    dest: /tmp/tmp.gz

- name: Compress regular file /path/to/foo into /path/to/foo.gz and remove it
  archive:
    path: /var/www/html/index.html
    remove: yes

- name: Create a bz2 archive of multiple files, rooted at /path
  archive:
    path:
    - /tmp
    - /var/www/html
    dest: /var/www/backup.tar.bz2
    format: bz2
