---
- name: Create a directory if it does not exist
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Create a empty file
  file:
    path: /var/www/html/index.html
    state: touch
    mode: u=rw,g=r,o=r
