---
- name: adding a line
  lineinfile:
    path: /tmp/script.sh
    regexp: '^System:'
    line: "System: Linux"

- name: Deleting a line
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^%wheel'

- name: Replace a line only after a specified string
  lineinfile:
    path: /tmp/script.sh
    insertafter: '^Tools: '
    line: "Manage by: Ansible"
