---
- name: Examples of common modules
  include_tasks: "{{ module }}.yml"
  loop_control:
    loop_var: module
  loop:
    - apt
    - file
    - template
    - blockinfile
    - cron
    - group
    - ping
    - replace
    - shell
    - user
    - command
    - debug
    - find
    - include_vars
    - npm
    - pip
    - script
    - yum
    - archive
    - get_url