---
- name: Install NGINX
  package:
    name: nginx
    state: present
  become: true

- name: Install the latest version of Apache
  package:
    name:
      - apache2
    state: latest
  become: true