---
- name: Install NGINX
  package:
    name: nginx
    state: present
  become: true

- name: Install the latest version of Apache and MongoDB
  package:
    name:
      - apache2
      - mongodb
    state: latest
  become: true