---
- name: Template a script
  template:
    src: script
    dest: /tmp/script.sh
    owner: root
    group: www-data
    mode: 'u=x'

- name: Template requirements
  template:
    src: requirements
    dest: /tmp/requirements.txt
